### ISSUE TITLE
Timeout setting doesn't work in the z3 check procedure

### ISSUE THREAD

**Issue by xuyoji** [RafaelTupynamba/quicksampler#10]
For example,  I use this instruction to check 800000 samples of qucksampler.
`z3 sat.quicksampler_check=true sat.quicksampler_check.timeout=50 Benchmarks/56.sk_6_38.cnf`
it will never stop within 50 seconds, on the contray, it stop at 359 seconds.

**Comment by RafaelTupynamba** [comment]
Should be fixed with the latest commit.
