### ISSUE TITLE
Fails on large CNF formulae

### ISSUE THREAD

**Issue by AniOjha** [RafaelTupynamba/quicksampler#8]
I find while using quicksampler as a static library that it works on formulae with a small number of clauses, while it calls larger formulae UNSAT erroneously (cross-checked them with MiniSAT). Could you please give me pointers as to what might be the reason?

**Comment by RafaelTupynamba** [comment]
Our solve() function indeed treats equally the cases where the solver returns z3::unsat or z3::unknown (if solver times out/can't solve). In our follow-up work SMTSampler we improved on this by actually trying to solve again without the soft constraints when the solver times out.

I can try adding some of those improvements into QuickSampler.
Do you have an example formula where this problem happens? Does your formula specify an independent support or are all variables considered to be in the independent support?

You can check out SMTSampler here:
https://github.com/RafaelTupynamba/SMTSampler
SMTSampler expects a formula in SMT-LIB format.

SMTSampler also has more scalability improvements to handle formulas with a large number of variables. The benchmarks we used for QuickSampler had a relatively small number of variables in the independent support.

**Comment by AniOjha** [comment]
What is happening is that on running it, it terminates immediately, not after running after some time until it is called a timeout/UNSAT. I am uploading a few files here - the variables are specified as independent.


[1_bmark.txt](https://github.com/RafaelTupynamba/quicksampler/files/2603659/1_bmark.txt)
[5_bmark.txt](https://github.com/RafaelTupynamba/quicksampler/files/2603660/5_bmark.txt)

**Comment by RafaelTupynamba** [comment]
Hi, the problem was that the empty line at the end of the file was interpreted as an empty clause, which is always false.
I updated the code to fix this.
But since those formulas have more than 2000 variables to sample from, QuickSampler will probably not perform well. You might wanna check out SMTSampler. SMTSampler expects the formula to be provided in the .smt2 file format. It will probably perform much better for your benchmarks.
