### ISSUE TITLE
Questions about install and execute

### ISSUE THREAD

**Issue by z971586668** [RafaelTupynamba/quicksampler#9]
1. If I use the z3 patch, it will give a syntax error after the dowloading. I have a clean environment without z3 before installing it.
2. If I skip the z3 patch and installed it with the original version, when I run quicksampler with
./quicksampler -n 10000000 -t 7200.0 formula.cnf
it gives an error of 
Error opening input files

**Comment by z971586668** [comment]
Sorry but I know what I did wrong in the second question.
And also, what is meaning of the output 

Samples 1676116
Execution time 10.111

Does it means there are 1676116 samples but only  need 10.111 time units?

**Comment by RafaelTupynamba** [comment]
Hi, thank you for reporting.

1) I made a new commit for the patch to work on the current version of z3
2) Yeah, formula.cnf needs to be a valid path to a file with the formula.
3) Number of samples produced so far. Execution time so far in seconds.
